title: TagRepo - A tool to assign and query tags on files in a filesystem
subtitle: BSc Computer Science
author:
- Chun Ho Wong (200530468)
- Dr. Johan Pauwels
bibliography: src/bibliography.bib
csl: config/harvard-cite-them-right.csl
