# This inherits settings from input-files.yml
defaults: input-files.yml
from: markdown

metadata-file: meta.yml
filters:
  - pandoc-crossref
  - citeproc
toc: true
highlight-style: kate
number-sections: true
