# This inherits settings from ./common.yml
defaults: config/pandoc/common.yml

from: markdown+rebase_relative_paths
filters:
  - config\rebase-image-paths.lua
output-file: docs/index.html
to: html
standalone: true
metadata:
  fontsize: 16px
  fontcolor: '#444'
  backgroundcolor: white
