# This inherits settings from ./common.yml
defaults: config/pandoc/common.yml

output-file: docs/index.html
to: html
standalone: true
metadata:
  fontsize: 16px
  fontcolor: '#444'
  backgroundcolor: white
