input-files:
- src/presentation.md
from: markdown

metadata-file: meta.yml
highlight-style: kate
citeproc: true

output-file: docs/presentation.pdf
to: beamer
template: templates/beamer.tex
metadata:
  logo: src/logo.png
