name: Pandoc Action

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Create PDF using pandoc
      - uses: docker://pandoc/latex:3.1.1
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
             tlmgr update --self &&
             tlmgr install fvextra lineno &&
             pandoc --defaults config/pandoc/pdf.yml
            "

      # Create HTML using pandoc
      - uses: docker://pandoc/latex:3.1.1
        with:
          args: --defaults config/pandoc/html.yml --embed-resources

      # Create presentation using pandoc
      - uses: docker://pandoc/latex:3.1.1
        with:
          args: --defaults config/pandoc/presentation.yml

      # Commit all changes to a new branch
      - name: Commit changes and push to a new branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_checkout: true
          skip_fetch: true
          create_branch: true
          branch: pandoc-action
          file_pattern: docs/*.pdf docs/*.html
          add_options:  --force
          commit_message: Pandoc action
          commit_options: --signoff
          push_options: --force
          skip_dirty_check: true
